### ISSUE TITLE
Program doesn't seem to exit

### ISSUE THREAD

**Issue by tastewar** [thoqbk/pi-oi#1]
When I run your program as suggested, via `java -jar pi-oi.jar` it seems to just hang after displaying results and printing your name. I am running "the latest" version of Java (on Windows):

`java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)`

**Comment by thoqbk** [comment]
Hi, it's because I used System.in.read() at the end of the program. So just press enter to make it exit. Thank you!

**Comment by tastewar** [comment]
Thanks for the explanation. It's helpful to have a message like "Press Enter to exit" or something like that. Did you do this so that you could have a desktop shortcut to run the program and not have it close the window? If so, you can make a shortcut as follows:

`cmd.exe /k java -jar pi-oi.jar`

so the window doesn't close automatically. This will make your program easier to use in other scenarios (e.g. someone running it in a batch file)

**Comment by thoqbk** [comment]
Yes, I think I will add this soon. Thank you for your reply.
